# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy dependencies files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./cmd/

# Runtime stage
FROM alpine:latest
WORKDIR /root/

# Copy binary from build stage
COPY --from=builder /main .

# Expose application port (matches your .env APP_PORT)
EXPOSE ${APP_PORT}

# Command to run the application
ENTRYPOINT ["./main"]