services:
    db:
        image: postgres:17
        restart: always
        container_name: casa-oliveira-db
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:${DB_PORT}"
