services:
    db:
        image: postgres:17
        restart: always
        container_name: casa-oliveira-db
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:${DB_PORT}"

    app:
        build: .
        restart: always
        container_name: casa-oliveira-app
        env_file:
            - .env
        environment:
            DB_HOST: db
        ports:
            - "${APP_PORT}:${APP_PORT}"
        depends_on:
            - db
